### ISSUE TITLE
Crashes at unwrapped None in diff_view.rs

### ISSUE THREAD

**Issue by chrysn** [xfbs/diff.rs#3] opened 2023-03-08 20:22 UTC
There's a panic that happens when loading the coap-handler-implementations crate.

Example URI: https://diff.rs/coap-handler-implementations/0.4.1/0.4.2/src/

Error message:
```
panicked at 'called `Option::unwrap()` on a `None` value', src/components/diff_view.rs:88:47
```

**Comment by xfbs** [comment] 2023-03-08 20:54
Thanks for spotting this! Turns out I had introduced this regression. Should be fixed now, there was two paths in the code where it would panic if you are trying to view something that is not a file (in src/components/diff_view.rs:88) or a file that does not exist (in src/components/file_tree.rs). Just deployed the fixes, let me know if anything else causes it to panic!

**Closed by xfbs** 2023-03-08 20:54 UTC
